### ISSUE TITLE
Missing expansions after OP08

### ISSUE THREAD

**Issue by Sanjister** [seitrox/optcg-sim2cardmarket-converter#4]
Missing expansions after OP08 which was released 13th September, 2024:
- ST-15, ST-16, ST-17, ST-18, ST-19, ST-20, PRB01 & OP09

Thanks for the very helpful tool.

**Comment by Sanjister** [comment]
I've opened a PR https://github.com/seitrox/optcg-sim2cardmarket-converter/pull/3 with the updated data if it can help.

**Comment by seitrox** [comment]
Thanks for creating the PR.

Just merged it.
